### ISSUE TITLE
Add domains to mail filter

### ISSUE THREAD

**Issue by ThomSawyer** [briefmnews/briefme-validator#14]
tempr.email
freetmail.net
best-mail.net
businessagent.email
dreamcatcher.email
hotelnextmail.com
mini-mail.net
smart-mail.info
click-mail.net
quick-mail.online
mail4.online
newtmail.com

**Comment by ThomSawyer** [comment]
Deployed on Brief.eco

**Comment by ThomSawyer** [comment]
Deployed on Brief.me

**Comment by eespanel** [comment]
Ok.
