### ISSUE TITLE
Vérifier ou ajouter des domaines à notre filtre e-mail

### ISSUE THREAD

**Issue by ThomSawyer** [briefmnews/briefme-validator#21]
[hoymail.fr](http://hoymail.fr/) -> ajouté
[hotmsil.fr](http://hotmsil.fr/) -> ajouté
[hotmqil.fr](http://hotmqil.fr/) -> ajouté
[hotmaol.fr](http://hotmaol.fr/) -> déjà dans le filtre
[hotmal.fr](http://hotmal.fr/) -> déjà dans le filtre
[hotamil.fr](http://hotamil.fr/) -> ajouté
[hotail.fr](http://hotail.fr/) -> déjà dans le filtre
[homtmail.fr](http://homtmail.fr/) -> ajouté
[hitmail.fr](http://hitmail.fr/) -> ajouté
[hahoo.fr](http://hahoo.fr/) -> ajouté
[wanaddoo.fr](http://wanaddoo.fr/) -> ajouté
[test.fr](http://test.fr/) -> ajouté
spambox.me -> ajouté
[hotmzil.fr](http://hotmzil.fr/) -> ajouté
[hormail.fr](http://hormail.fr/) -> ajouté
[clu-internet.fr](http://clu-internet.fr/) -> ajouté
[lappste.net](http://lappste.net/) -> ajouté
[iclooud.com](http://iclooud.com/) -> ajouté
[gemil.com](http://gemil.com/) -> ajouté
[irange.fr](http://irange.fr/) -> ajouté
[uahoo.fr](http://uahoo.fr/) -> ajouté

1. ajouter au filtre e-mail
2. Corriger ceux arrivés dans les 30 derniers jours
3. Supprimer me, eco et sci (attention active, trialing, past_due)

**Comment by ThomSawyer** [comment]
Snippet : 
```python
from validator.constants import *

domains = DISPOSABLE_EMAIL_DOMAINS + PHISHING_DOMAINS
user_emails = []
for domain in domains:
    users = User.objects.filter(email__icontains=domain)
    for u in users:
        user_emails.append(u.email)
```

**Comment by ThomSawyer** [comment]
me (3 adresses e-mails corrigées) : 
* echatel@homail.fr
* mcbmetas@yaoo.fr
* lenaigsalaun013@gamil.com

**Comment by ThomSawyer** [comment]
eco 

21 suppressions de comptes

**Comment by ThomSawyer** [comment]
sci 

31 suppressions de comptes

**Comment by williamdes** [comment]
Voir https://github.com/betagouv/rdv-solidarites.fr/issues/3406#issuecomment-1615901641 pour d'autres domaines

**Comment by williamdes** [comment]
et une autre belle liste https://github.com/ericabouaf/webhookit/blob/13abf6f072e23d536432235da78fd3e4e5d742b6/public/javascripts/inputex/js/fields/EmailField.js#L38-L71
